"""empty message

Revision ID: fa0f08e76881
Revises: 
Create Date: 2018-04-23 12:29:08.200827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0f08e76881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('z_cities',
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('StateName', sa.String(length=64), nullable=True),
    sa.Column('MSAName', sa.String(length=64), nullable=True),
    sa.Column('UWHomes_AllTiers', sa.Float(), nullable=True),
    sa.Column('UWHomes_TotalValue_AllTiers', sa.Float(), nullable=True),
    sa.Column('AllHomes_AllTiers_ShareUW', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('image', sa.String(length=80), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('transaction',
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('B_name', sa.String(length=40), nullable=True),
    sa.Column('B_email', sa.String(length=40), nullable=True),
    sa.Column('B_address', sa.String(length=70), nullable=True),
    sa.Column('B_city', sa.String(length=30), nullable=True),
    sa.Column('B_state', sa.String(length=15), nullable=True),
    sa.Column('B_zip', sa.Integer(), nullable=True),
    sa.Column('P_NameonCard', sa.String(length=40), nullable=True),
    sa.Column('CC_number', sa.String(length=40), nullable=True),
    sa.Column('exp_month', sa.String(length=15), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('cvv', sa.Integer(), nullable=True),
    sa.Column('sumtotal', sa.Float(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('t_id')
    )
    op.create_table('join_table',
    sa.Column('j_id', sa.Integer(), nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['transaction.t_id'], ),
    sa.PrimaryKeyConstraint('j_id')
    )
    op.create_table('kart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kart')
    op.drop_table('join_table')
    op.drop_table('transaction')
    op.drop_table('product')
    op.drop_table('z_cities')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
